### ISSUE TITLE
Create copies for website

### ISSUE THREAD

**Issue by eluciano11** [fullstacknights/website#1]
Currently, the website only has placeholder text that should be replaced with the actual copy that we want to use. The copies should be created in English and Spanish.

- [x] Home Page
- [ ] About Page
- [ ] Become a Moderator Page
- [ ] Become a Speaker Page
- [x] Schedule

**Comment by eluciano11** [comment]
Home
  - Header
    - Fullstack Nights
    - A space for people to share their knowledge about code and design.
  - Be a part of our events
    - The Fullstack Nights events are done by the community for the community. Without your participation we cannot keep these events going.
    - Become a speaker
      - We're looking for people who are willing to share their experiences with the community through presentations. Speakers can be experts or people learning about a topic. If you're interested in sharing your experience programming or designing let us know. We'll help you craft your presentation.
    - Become a moderator
      - We're looking for people knowledgeable people that are willing to moderate a discussion. Moderators will talk about a topic with beginners and experienced professionals. The goal is for everyone to learn and share their experience through conversations.
    - Propose a topic
      - Interested in having a conversation about a particular topic but you don't feel confident to moderate a table or give a presentation? Don't worry, you can propose your topic and we'll try to find someone who's willing to share their knowledge and moderate a table.
  - Podcast
    - Listen to the founds of Fullstack Nights geek out about technology and events in the tech world in a relaxed environment.
  - Join the community in Slack
    - Ask questions, get help from the community and stay up to date with the latest events.

@froi @rnegron feedback please

**Comment by froi** [comment]
@eluciano11 

Fixed some typos in your OP.

This is great. Would it be useful to add distinction between what's for topic tables and what's for the talks? For example, `Become a moderator` is specifically for Topic Tables not the talks event.

> We're looking for people who are willing to share their experiences with the community through presentations. 

I'd change `presentations` to ` talks`.

> If you're interested in sharing your experience programming or designing let us know.

I'd change this to `If you're interested in sharing your experience building, designing, or programming let us know!`

> We'll help you craft your presentation.

I'd move this to it's own bullet. Eg.

- Haven't given a talk before or need help polishing yours?
  - We can help! Part of our process is going through practice run of your talk and helping you make it the best it can be.

> The Fullstack Nights events are done by the community for the community. Without your participation we cannot keep these events going.

I'd change this to be a bit more informal. Something like `Our events are done by the community for the community. Without you there would be no us.`

> Moderators will talk about a topic with beginners and experienced professionals. 

I'd change this to `As a moderator you will help establish and move a topic along.`

**Comment by eluciano11** [comment]
> Would it be useful to add distinction between what's for topic tables and what's for the talks? For example, Become a moderator is specifically for Topic Tables not the talks event.

Agreed.

También hace falta añadir algo como "events" en el landing page. Ahora mismo no dice cuales son los eventos que tenemos. Eso le puede dar más contexto a las personas que entran por primera vez a la página o a las personas que nunca han ido a FSN.

![home](https://user-images.githubusercontent.com/6109151/69011305-a7bd1d80-093f-11ea-9b26-26aaf12c6b61.png)

Cuando dices:
> I'd move this to it's own bullet. Eg.
Haven't given a talk before or need help polishing yours?
We can help! Part of our process is going through practice run of your talk and helping you make it the best it can be.

Te refieres a añadir otro card?

Agreed con lo demás también. Will change.

**Comment by froi** [comment]
Not another card. Me fui literal con el "bullet" en el issue. 😝 

Make it it's own paragraph if it fits in the design.

**Comment by eluciano11** [comment]
@froi @rnegron moar feedback please.

Become a speaker
  - Header
    - Give a talk at Fullstack Nights!
    - We're constantly looking for speakers. Join us!
  - We'll help you craft your presentation
    - We are committed to help you give the best talk possible. Before your talk we'll take the following steps:
      - Topic scoping
        - Before you're selected as a speaker we'll research your topic. If your topic is too broad we'll discuss different approaches to narrow down your topic.
      - Talk rehearsal
        - Two weeks before the event we'll rehearse the talk with you. We'll give you feedback about the structure of your talk, your delivery and the time you consumed presenting.
      - Slides evaluation
        - During your talk rehearsal we'll evaluate the content in your slides and give you pointers that will visually improve your presentation.

Para que tengan contexto de cómo se ve:
![bas](https://user-images.githubusercontent.com/6109151/69011992-f28e6380-0946-11ea-8e88-7e22d5a4462b.png)

**Comment by eluciano11** [comment]
@froi @rnegron feedback please.

Schedule
  - Header
    - Schedule
    - The FSN team is punctual, please help us by arriving early to the venue.

**Comment by eluciano11** [comment]
Become a topic moderator
  - Header
    - Become a topic moderator
    - We’re constantly looking for moderators and topics for FSN Topic Tables. Join us!
    - Moderator
      - A moderator is someone who's knowledgeable about a specific topic and is willing to share their experience with others. As a moderator you will help establish and move a topic along. The goal is for everyone to learn and share their experience through conversations.
    - Topic
      - You don't have to be a moderator to participate on FSN Topic Tables. If you're interested in having a conversation about a particular topic but you don't feel confident to moderate a table or give a presentation? Don't worry, you can propose your topic and we'll do our best to find someone who's willing to moderate a table.

**Comment by eluciano11** [comment]
About
  - Header
    - About Fullstack Nights
    - Fullstack Nights is a monthly meetup where programmers and designers can share their experience and knowledge in an informal environment.

  - A brief introduction to FSN
    - What is Fullstack Nights?
      Fullstack Nights is a monthly meetup for programers and designers interested in learning and sharing their knowledge in an informal and relaxed environment. Fullstack Nights consists on two events: Speakers and Topic Tables. FSN Speakers is an event that consists of 2 presentations that have a length of 20 minutes each. The topics of each presentation can be programing languages, frameworks, tools, databases, user interfaces, users experience and any other topic that can be of interest to our community. Topic Tables aims to bring the community together to share conversations about different topics. Participants can ask questions, discuss ideas and expand their knowledge through a moderated conversation.
    
    - Why are we doing this?
      @froilan creo que esto lo debes escribir tu.

    - Who should attend to this event?
      Everyone who's interested in programming and interactive design. It doesn't matter if you're a student, an expert or if you just have a bit of curiosity about a topic. There's space for everyone to learn and share their experience.

    - What's the format of our event?
      Fullstack Nights has different formats depending on the event. FSN Speakers aims to provide talks from people who are experts or are learning about about a topic. FSN Topic Tables is a forum there people from different skill levels can ask questions, discuss ideas and provide guidance to others in an informal setting.

    - How can I get involved?
      You can get involved by becoming a speaker, becoming a moderator, proposing a topic or by joining our Slack community.
  
  - We don't tolerate idiotic behavior
    - Every Fullstack Nights participant has to accept our code of conduct. The organizers of the event will enforce our rules through out the event. We expect that every participant and organizer will help us provide a safe environment for everyone.

**Comment by rnegron** [comment]
Some feedback, nitpicks: 

> A space for people to share their knowledge about code and design.

I would change it to

> A space for everyone to learn and share their knowledge about code and design.

* Using "everyone" makes it immediately inclusive.
* Saying "a space for people" seems weird to me, sort of obvious that its for people I would say.
* Putting "learn" also invites people who don't have/want to share their knowledge but are still interested.

> The Fullstack Nights events are done by the community for the community. Without your participation we cannot keep these events going.

I would change it to 

> The Fullstack Nights events are done by the community, for the community. We depend on everyone's support in order to keep the events going.

* Notice the comma after the first "community".
* I think the second sentence seems a bit harsh, I would change it to be less aggressive and use friendlier words like "depend on" and "support".

> Speakers can be experts or people learning about a topic. If you're interested in sharing your experience programming or designing let us know. We'll help you craft your presentation.

I would change it to

> You don't have to be an expert in order to be a speaker! If you are passionate about a particular topic and would like to share it, you're welcome to submit a talk. Either way, we'll help by providing feedback along the way.

* More explicit about what we want to say related to experts vs. learners
* More motivating for those who are not experts, in my opinion
* More explicit about the help we will give as well

>  We're looking for knowledgeable people that are willing to moderate a discussion. 

I would change to

> We're looking for people with knowledge about a particular topic that are willing to moderate a discussion around that topic.

* Makes it clear that the moderators will handle one topic

> Moderators will talk about a topic with beginners and experienced professionals. The goal is for everyone to learn and share their experience through conversations.

I would change to 

> The goal is for beginners and experts alike to learn and share their experience through conversations.

* Shorter, includes both messages in one sentence.
         
> Interested in having a conversation about a particular topic but you don't feel confident to moderate a table or give a presentation? 

I would change to 

> Interested in having a conversation about a particular topic, but don't feel you're the right fit to moderate or become a speaker?

* Removes the word "confidence" so as not to make the reader feel bad about it
* Makes it more welcoming I think.

> Don't worry, you can propose your topic and we'll try to find someone who's willing to share their knowledge and moderate a table.

I would change to 

> Send us your topic ideas and we'll try to find someone interested in sharing their knowledge on your suggested topic!

* Flows better with the last sentence.
* Removes the word "worry".

>  Listen to the founders of Fullstack Nights geek out about technology and events in the tech world in a relaxed environment.

I like that one a lot lol

**Comment by rnegron** [comment]
>  We try to be as organized and punctual as possible, please checkout our schedule below.

I would change to 

> We try to be as organized and punctual as possible. Check out our schedule below.

* Splits the sentence in two, they seem to be different messages.
* Removes the word "please".
* Typo fix "checkout"

**Comment by eluciano11** [comment]
>A space for everyone to learn and share their knowledge about code and design.

Agreed 💯 

------

>The Fullstack Nights events are done by the community, for the community. We depend on everyone's support in order to keep the events going.

@froi suggested we use:
>Our events are done by the community for the community. Without you there would be no us.

I think we can combine all of them.

>Our events are done by the community, for the community. Without your support and participation there would be no us.

Thoughts?

------

> You don't have to be an expert in order to be a speaker! If you are passionate about a particular topic and would like to share it, you're welcome to submit a talk. Either way, we'll help by providing feedback along the way.

Agreed. This sounds a lot more encouraging. 

This would be the result:
>We're looking for people who are willing to share their experiences with the community through talks. You don't have to be an expert in order to be a speaker! If you are passionate about a particular topic and would like to share it, you're welcome to submit a talk. Either way, we'll help by providing feedback along the way.

------
>We're looking for people with knowledge about a particular topic that are willing to moderate a discussion around that topic.

>The goal is for beginners and experts alike to learn and share their experience through conversations.

Agreed, way better than the original one.

This would be the result:
> We're looking for people with knowledge about a particular topic that are willing to moderate a discussion around that topic. The goal is for beginners and experts alike to learn and share their experience through conversations.

------

> Interested in having a conversation about a particular topic, but don't feel you're the right fit to moderate or become a speaker?

>Send us your topic ideas and we'll try to find someone interested in sharing their knowledge on your suggested topic!

Agreed, this sounds a lot better. I didn't think the word "confidence" would make people feel bad but I understand your point. We should remove it. 

The result would be:
> Interested in having a conversation about a particular topic, but don't feel you're the right fit to moderate or become a speaker? Send us your topic ideas and we'll try to find someone interested in sharing their knowledge on your suggested topic!


@rnegron good feedback! Thank you very much for helping out!

**Comment by eluciano11** [comment]
## Home page copy updates

Home
  - Header
    - Fullstack Nights
    - A space for everyone to learn and share their knowledge about code and design.
  - Be a part of our events
    - Our events are done by the community, for the community. Without your support and participation there would be no us.
    - Become a speaker
      - We're looking for people who are willing to share their experiences with the community through talks. You don't have to be an expert in order to be a speaker! If you are passionate about a particular topic and would like to share it, you're welcome to submit a talk. Either way, we'll help by providing feedback along the way.
    - Become a moderator
      - We're looking for people with knowledge about a particular topic that are willing to moderate a discussion around that topic. The goal is for beginners and experts alike to learn and share their experience through conversations.
    - Propose a topic
      - Interested in having a conversation about a particular topic, but don't feel you're the right fit to moderate or become a speaker? Send us your topic ideas and we'll try to find someone interested in sharing their knowledge on your suggested topic!
  - Podcast
    - Listen to the founders of Fullstack Nights geek out about technology and events in the tech world in a relaxed environment.
  - Join the community in Slack
    - Ask questions, get help from the community and stay up to date with the latest events.

**Comment by froi** [comment]
@rnegron https://github.com/fullstacknights/website/issues/1#issuecomment-555310693 are excellent. Thank you!
