### ISSUE TITLE
Create Q/A list

### ISSUE THREAD

**Issue by eluciano11** [fullstacknights/website#2]
Create Q/A list for the following sections:

- [x] Become a Moderator Page
- [x] Become a Speaker Page
- [x] About Page

**Comment by eluciano11** [comment]
Become a speaker:
  - What can I speak about?
    You're welcomed to speak about programing languages, frameworks, tools, databases, infrastructure, email design, user interfaces, users experience, prototyping and any other topic or experience that can add value to our community.
  - How much time to I have to give my talk?
    The talk will be 20 minutes and 5 minutes of Q&A after the presentation is over.
  - I recently learned about a new technology, can I speak about it?
    Yes, of course! When we've just learned about a topic we have a unique perspective compared to an expert. Don't count yourself out and apply as a speaker!
  - Can I recommend someone to speak at this event?
    Yes! If you know someone that would be a good speaker at FSN you can apply on their behalf and we'll reach out to them.
  - I've never done any public speaking before, should I apply as a speaker?
    Yes, you should! The FSN team is here to help you give the best talk possible! Before the event we'll rehearse the talk with you, give you feedback and help you polish your presentation.

**Comment by rnegron** [comment]
>   Yes, of course! When we've just learned about a topic we have a unique perspective compared to an expert. Don't count yourself out and apply as a speaker!

>  Yes, you should! The FSN team is here to help you give the best talk possible! Before the event we'll rehearse the talk with you, give you feedback and help you polish your presentation.

Nice ones 👍

**Comment by eluciano11** [comment]
# Become a moderator:
  - What is topic tables?
    Topic Tables is an event that brings together the community to talk about different topics in a relaxed and informal environment. Participants will be able to ask questions, talk about their experience and learn from others through moderated conversations.
  - Who should attend to this event?
    Anyone who's interested in programming and design. It doesn't matter if you're a student, beginner or an expert. There's space for everyone to learn and grow.

**Comment by eluciano11** [comment]
- What is Fullstack Nights?
      Fullstack Nights is a monthly meetup for programers and designers interested in learning and sharing their knowledge in an informal and relaxed environment. Fullstack Nights consists on two events: Speakers and Topic Tables. FSN Speakers is an event that consists of 2 presentations that have a length of 20 minutes each. The topics of each presentation can be programing languages, frameworks, tools, databases, user interfaces, users experience and any other topic that can be of interest to our community. Topic Tables aims to bring the community together to share conversations about different topics. Participants can ask questions, discuss ideas and expand their knowledge through a moderated conversation.
    
    - Why are we doing this?
      @froi creo que esto lo debes escribir tú.

    - Who should attend to this event?
      Everyone who's interested in programming and interactive design. It doesn't matter if you're a student, an expert or if you just have a bit of curiosity about a topic. There's space for everyone to learn and share their experience.

    - What's the format of our event?
      Fullstack Nights has different formats depending on the event. FSN Speakers aims to provide talks from people who are experts or are learning about about a topic. FSN Topic Tables is a forum there people from different skill levels can ask questions, discuss ideas and provide guidance to others in an informal setting.

    - How can I get involved?
      You can get involved by becoming a speaker, becoming a moderator, proposing a topic or by joining our Slack community.

**Comment by froi** [comment]
@eluciano11 Dude this is awesome. Gracias por hacer esto.

Some comments on https://github.com/fullstacknights/website/issues/2#issuecomment-555301143

> You're welcomed to speak 

You're welcome to speak.

> The talk will be 20 minutes and 5 minutes of Q&A after the presentation is over.

You'll have 20 minutes for your talk and 5 minutes for Q&A.

> Yes, of course!

Of course!

> The FSN team is here to help you give the best talk possible!

The FSN team is here to help you give the best talk possible.

> Before the event we'll rehearse the talk with you, give you feedback and help you polish your presentation.

We'll set up rehearsal sessions, provide feedback and help you polish your presentation.

> You can get involved by becoming a speaker, becoming a moderator, proposing a topic or by joining our Slack community.

There are a couple of way to get involved. Become a speaker or moderator, propose a topic, or join our Slack community.

**Comment by froi** [comment]
Comments for https://github.com/fullstacknights/website/issues/2#issuecomment-557829745

> ## Become a moderator:

The text that follows says nothing about being a moderator. Shouldn't this be `## Topic Tables`? Should we have a sub-topic for this, 

```
### Become a moderator?

Want to propose a topic and help a table have a great conversation? Join us as a moderator! To be a moderator you should have some knowledge of the topic, help guide the conversation at your table and be willing to have fun 😄.
```

> * What is topic tables?

What are topic tables?

>   Topic Tables is an event that brings together the community to talk about different topics in a relaxed and informal environment. Participants will be able to ask questions, talk about their experience and learn from others through moderated conversations.

I'm thinking about this one. For now let's use it.

> * Who should attend to this event?
>   Anyone who's interested in programming and design. It doesn't matter if you're a student, beginner or an expert. There's space for everyone to learn and grow.

Anyone who's interested in technology and design. It doesn't matter if you're a student, beginner or an expert. There's space for everyone to learn and grow.

**Comment by froi** [comment]
I did some substantial changes to the About page so I'm not quoting it.

## About page

* What is Fullstack Nights?

  Fullstack Nights is a monthly meetup for technologist and designers interested in learning and sharing their knowledge in an informal and relaxed environment.

* What's the format of our event?

  Great question! We actually have two events: __FSN Speakers__ and __FSN Topic Tables__. 

  FSN Speakers is an event that consists of two 20 minute talks, an open mic session, and some networking time. Past topics have ranged from introductions to programming frameworks to user experience in event design.

  FSN Topic Tables aims to bring the community together to share conversations about different topics. Participants can ask questions, discuss ideas and expand their knowledge through a __moderated__ conversation.

* Who should attend to this event?

  Everyone who's interested in technology and interactive design. It doesn't matter if you're a student, an expert or if you just have a bit of curiosity about a topic. There's space for everyone to learn and share their experience.

* Why are we doing this?

  The simple answer is, we ❤️  community. From the start our goal has been to provide value and bring together the different communities working around tech and startups. From our point of view sharing our experiences across disciplines makes the over all community stronger.

  We also wanted to meet people and provide a safe place where people can network and grow. We hope you'll join us in this journey. 

* How can I get involved?

  There's a number of ways. You can become a speaker or topic table moderator, you can propose a topic, or you can join our Slack community.

**Comment by froi** [comment]
@eluciano11 dale un vistazo y gracias por todo el trabajo ❤️

**Comment by eluciano11** [comment]
De nada! :D Gracias por el feedback! Los cambios están buenos, ya los apliqué.

**Comment by eluciano11** [comment]
Updated copies

## About
  - Header
    - About Fullstack Nights
    - Fullstack Nights is a monthly meetup where programmers and designers can share their experience and knowledge in an informal environment.

  - A brief introduction to FSN
    - What is Fullstack Nights?
      Fullstack Nights is a monthly meetup for technologist and designers interested in learning and sharing their knowledge in an informal and relaxed environment.
    
    - What's the format of our event?
      Great question! We actually have two events: FSN Speakers and FSN Topic Tables.

      FSN Speakers is an event that consists of two 20 minute talks, an open mic session, and some networking time. Past topics have ranged from introductions to programming frameworks to user experience in event design.

      FSN Topic Tables aims to bring the community together to share conversations about different topics. Participants can ask questions, discuss ideas and expand their knowledge through a moderated conversation.
    
    - Why are we doing this?
      @froilan creo que esto lo debes escribir tu.

    - Who should attend to this event?
      Everyone who's interested in programming and interactive design. It doesn't matter if you're a student, an expert or if you just have a bit of curiosity about a topic. There's space for everyone to learn and share their experience.

    - What's the format of our event?
      Fullstack Nights has different formats depending on the event. FSN Speakers aims to provide talks from people who are experts or are learning about about a topic. FSN Topic Tables is a forum there people from different skill levels can ask questions, discuss ideas and provide guidance to others in an informal setting.

    - How can I get involved?
      There are a couple of way to get involved. Become a speaker or moderator, propose a topic, or join our Slack community.
  
  - We don't tolerate idiotic behavior
    - Every Fullstack Nights participant has to accept our code of conduct. The organizers of the event will enforce our rules through out the event. We expect that every participant and organizer will help us provide a safe environment for everyone.

## Speakers
  - What can I speak about?
    You're welcome to speak about programing languages, frameworks, tools, databases, infrastructure, email design, user interfaces, users experience, prototyping and any other topic or experience that can add value to our community.
  - How much time to I have to give my talk?
    You'll have 20 minutes for your talk and 5 minutes for Q&A after the presentation is over.
  - I recently learned about a new technology, can I speak about it?
    Of course! When we've just learned about a topic we have a unique perspective compared to an expert. Don't count yourself out and apply as a speaker!
  - Can I recommend someone to speak at this event?
    Yes! If you know someone that would be a good speaker at FSN you can apply on their behalf and we'll reach out to them.
  - I've never done any public speaking before, should I apply as a speaker?
    Yes, you should! The FSN team is here to help you give the best talk possible. We'll set up rehearsal sessions, provide feedback and help you polish your presentation.

## Topic Tables
  - What are topic tables?
    Topic Tables is an event that brings together the community to talk about different topics in a relaxed and informal environment. Participants will be able to ask questions, talk about their experience and learn from others through moderated conversations.
  - Who should attend to this event?
    Anyone who's interested in technology and design. It doesn't matter if you're a student, beginner or an expert. There's space for everyone to learn and grow.
