### ISSUE TITLE
Contact links in Code of Conduct page

### ISSUE THREAD

**Issue by froi** [fullstacknights/website#32]
The `Need Help` section needs to have likes on how to contact the organizer.

Maybe add a link to each of the organizers Twitter profile?

Maybe it would be good to give access to the FSN account to the organizers have one person be in charge of watching any reports.

Ideally we would have an anonymous way to report these things.

**Comment by eluciano11** [comment]
Agreed with both of the suggestions.

@rnegron mentioned that he was going to add a PR later today to link the twitter profile of every organizer.

**Comment by froi** [comment]
@rnegron when making the PR please add `Closes #32` to it. Thanks!
