### ISSUE TITLE
Move forms to Netlify

### ISSUE THREAD

**Issue by eluciano11** [fullstacknights/website#42]

**Comment by froi** [comment]
Can you elaborate? What exactly do you want this to do? Is it just embedding the forms?

![giphy (2)](https://user-images.githubusercontent.com/1918027/70806863-3cbe0580-1d8a-11ea-8d48-b8d08dc4e6c3.gif)

**Comment by froi** [comment]
Hey @eluciano11. Creo que #43 y el PR #44 resuelven parte de esto.

¿Ademas de asegurar que las formas utilizen Netlify, que hace falta?

**Comment by eluciano11** [comment]
@froi cuando cree este issue estaba pensando que seria bueno mover todos los forms a Netlify primordialmente pq ellos te permiten tomar "acciones" cuando alguien complete un form. Entre las acciones disponibles esta enviar una notificación que Slack. Estaba pensando que seria una buena idea crear un channel (puede ser privado o publico) en el workspace de Startups of Puerto Rico para estar in the loop sobre los submissions que las personas hacen.

That being said, no sé si debemos hacerlo para todos los forms pq hay algunos que se pueden complicar. Por ejemplo, el Yearly Feedback Form es un poquito más complejo y nos daria más trabajo moverlo aca.

Podemos verificar si Google Forms y Typeform tienen webhooks services y tratar de integrarlos con Slack. Thoughts?

También pienso que tener toda esa data en varios servicios no es muy util. A mi me gusta la idea de tirar esa data a algo como Airtable o Notion para poder visualizarla mejor. Por ejemplo, con Airtable podemos tener un Kanban con los submitions, cuales estan en proceso, cuales ya escogimos, cuales descartamos, etc.

**Comment by froi** [comment]
100% agree con el tener esta data. Me gustaría ver como podemos hacer esta data disponible al publico anonimizada. Se que Notion tiene una manera de hacerlo, no se si Airtable. Me gustaría que no haga falta tener una cuenta en un servicio para ver esta data y que la data se pueda exportar a cualquier otro sito si queremos.

Los cambios en #44 permite configurar la forma que se esta creando de una manera que no esta atada a Netlify.

**Comment by froi** [comment]
@eluciano11 Esto fue cerrado por el GitHub Action. Tu que tu crees de reabrir este issue? Me parece que tiene parte ya hecho verdad?

**Comment by eluciano11** [comment]
Hay un form que lo tenemos en Netlify. Los demás los podemos mover luego pero no creo que haga falta reabrir el issue pq no creo que tengamos tiempo de trabajar en esto ahora.
