### ISSUE TITLE
404 Page is broken

### ISSUE THREAD

**Issue by eluciano11** [fullstacknights/website#48]
The 404 page looks like its broken. We should add some styling to it.

![image](https://user-images.githubusercontent.com/6109151/71720836-6ef6dc00-2df9-11ea-9676-d2ddbab3efb2.png)

**Comment by froi** [comment]
> the sadness

I vote we add sad David Tennant in the rain to the design

![](https://media.giphy.com/media/a9xhxAxaqOfQs/source.gif)

**Comment by eluciano11** [comment]
done by @FutoRicky, thanks for the help!
